# Changes here will be overwritten by Copier
#
# Updating `_src` could be helpful, see notes at:
# https://github.com/level12/coppy/wiki#creating-a-project
#
# Otherwise, NEVER EDIT MANUALLY
_commit: v1.20251025.1
_src_path: gh:level12/coppy
author_email: caleb.syring@level12.io
author_name: Caleb Syring
gh_org: calebsyring
gh_repo: critic
hatch_version_tag_sign: false
project_name: Critic
py_module: critic
python_version: '3.13'
script_name: critic
use_circleci: false
use_gh_nox: true
