project-org = 'Level 12'
image-name = 'critic'

policy-arns = [
    'arn:aws:iam::089600762287:policy/CriticDDBAccessQA'
]

[deployed-env]
CRITIC_NAMESPACE = 'qa'
MAILGUN_API_KEY = 'op://critic/mailgun/password'
MAILGUN_DOMAIN = 'mg.level12.io'
MAILGUN_FROM = 'critic@level12.io'
SLACK_BOT_TOKEN = 'op://critic/slack_bot_token/password'

[event-rules.run-due-checks]
action='run_due_checks'
cron = '* * * * ? *'  # Every minute on the minute
